services:
  redis:
    # скачиваем самый свежий образ редиса
    image: redis:latest
    # всегда перезагружаем контейнер если он упадёт
    restart: always
    # проброс портов - оказалось это было необязательно
    ports:
      - '6379:6379'
  app:
    build:
      # может быть путём или url в репозиторий git
      context: ./app # указывает контекст для COPY и ADD относительно указанной директории
    depends_on: # не запустит этот контейнер пока не поднимется контейнер redis
      - redis
    ports:
      - '8000:8000' # проброс с 8000 порта хоста на 8000 порт контейнера (там где слушает uvicorn)
  sub:
    build:
      context: ./sub
    depends_on:
      - redis